baseURL = 'https://gettheanchor.org/'
languageCode = 'en-us'
title = 'The Anchor'

enableRobotsTXT = true
# For Netlify builds, use absolute URLs in production. We'll keep relative for local file opens via relURL in templates.
relativeURLs = false

[pagination]
  pagerSize = 10

[permalinks]
  devotionals = '/devotionals/:slug/'

[params]
  description = 'Finding our way to Jesus, one verse at a time.'
  author = 'humble'
  twitter = ''
  substack_embed = ''

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[outputs]
  home = ['HTML', 'RSS']