baseURL = 'https://gettheanchor.org/'
languageCode = 'en-us'
title = 'The Anchor'

enableRobotsTXT = true
# Enable relative URLs so assets resolve correctly on Netlify preview domains *and* custom domain.
# We will switch helpers in templates from absURL to relURL.
relativeURLs = true

[pagination]
  pagerSize = 10

[permalinks]
  devotionals = '/devotionals/:slug/'
  articles = '/articles/:slug/'
  social = '/social/:year/:month/:slug/'
  series = '/series/:slug/'

[taxonomies]
  tag = 'tags'
  category = 'categories'
  series = 'series'

[params]
  description = 'Finding our way to Jesus, one verse at a time.'
  author = 'humble'
  substack = 'https://humblenv.substack.com/'
  youtube = 'https://www.youtube.com/@TheAnchorInTheStorm'
  twitter = 'https://x.com/humble_nv'
  instagram = 'https://www.instagram.com/theanchorinthestorm'
  facebook = 'https://www.facebook.com/theanchorinthestorm'
  tiktok = 'https://www.tiktok.com/@humble_nv'
  default_og_image = '/images/default-og.svg'
  substack_embed = '<iframe src="https://humblenv.substack.com/embed" width="480" height="320" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no"></iframe>'
  # Homepage banner image (can be an absolute URL or a path under /static)
  banner_image = '/images/banner.webp'
  banner_alt = 'The Anchor banner'
  twitter_handle = 'humble_nv'
  logo_url = 'https://substackcdn.com/image/fetch/w_80,h_80,c_fill,f_webp,q_auto:good,fl_progressive:steep,g_auto/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2Fa7debb99-6122-4ef4-bf85-941f3a5a2dde_722x722.png'
  # Switch homepage layout: 'default' or 'conversion'
  # Set to 'refined' to enable the new Refined Neutral Option 1 design
  homepage_variant = 'refined'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[outputs]
  home = ['HTML', 'RSS']