# Intentionally minimal. Primary site configuration lives in config.toml.
# Keeping this file to avoid confusion with Hugo modules.

title = 'The Anchor'

[params]
  homepage_variant = 'refined'
  logo_url = '/images/the-anchor-logo.webp'
  substack_embed = '<iframe src="https://humblenv.substack.com/embed" width="480" height="320" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no"></iframe>'
  substack = 'https://humblenv.substack.com/'
  youtube = 'https://www.youtube.com/@TheAnchorInTheStorm'
  twitter = 'https://x.com/humble_nv'
  instagram = 'https://www.instagram.com/theanchorinthestorm'
  facebook = 'https://www.facebook.com/theanchorinthestorm'
  tiktok = 'https://www.tiktok.com/@humble_nv'

[module]
  # You can pin Hugo version constraints here if needed in the future.
  [module.hugoVersion]
    extended = true
